
// Create an Object
export const player_character = {
    abilityList: ["Agility", "Animal_Handling", "Athletics", "Awareness", "Cunning", "Deception", "Endurance", "Fighting", "Healing", "Knowledge", "Marksmanship", "Persuasion", "Status", "Stealth", "Survival", "Thievery", "Warfare","Will", "Language"],
    "Agility": ["Acrobatics", "Balance", "Contortions", "Dodge", "Quickness"],
    "Animal_Handling": ["A_Charm", "Drive", "Ride", "Train"],
    "Athletics":["Climb", "Jump", "Run", "Strength", "Swim", "Throw"],
    "Awareness": ["Empathy", "Notice"],
    "Cunning": ["Decipher", "Logic", "Memory"],
    "Deception": ["Act", "Bluff", "Cheat", "Disguise"],
    "Endurance": ["Resilience", "Stamina"],
    "Fighting": ["Axes", "Bludgeons", "Brawling", "Fencing", "Long_Blades", "Pole_Arms", "Short_Blades", "Shields", "Spears"],
    "Healing": ["Diagnose", "Treat_Ailment", "Treat_Injury"],
    "Knowledge": ["Education", "Research", "Streetwise"],
    "Marksmanship": ["Bows", "Crossbows", "Siege", "Thrown"],
    "Persuasion": ["Bargain", "Charm", "Convince", "Incite", "Intimidate", "Seduce", "Taunt"],
    "Status": ["Breeding", "Reputation", "Stewardship", "Tournaments"],
    "Stealth": ["Blend_In", "Sneak"],
    "Survival": ["Forage", "Hunt", "Orientation", "Track"],
    "Thievery": ["Pick_Lock", "Sleight_of_Hand", "Steal"],
    "Warfare": ["Command", "Strategy", "Tactics"],
    "Will": ["Concentrate", "Coordinate", "Dedication"],
    "Language": ["Native_language"],

    
};

export const player_Erling = {
    abilityList: [4,2,2,3,5,2,2,5,2,2,2,3,2,3,2,2,2,2,1],
    "Agility": [0,0,0,0,0],
    "Animal_Handling": [0,0,0,0],
    "Athletics":[0,0,0,0,0,0],
    "Awareness": [0,0],
    "Cunning": [0,2,2],
    "Deception": [0,0,0,0],
    "Endurance": [0,0],
    "Fighting": [0, 0, 2, 0, 0, 0, 1, 0, 0],
    "Healing": [0,0,0],
    "Knowledge": [0,0,0],
    "Marksmanship": [0,0,0,0],
    "Persuasion": [0,0,0,0,0,0,0],
    "Status": [0,0,0,0],
    "Stealth": [1,0],
    "Survival": [0,0,0,0],
    "Thievery": [0,0,0],
    "Warfare": [0,0,0],
    "Will": [0,0,0],
    "Language": [1],
    age: 28,
    house: "Torshalla", 
    name: "Erling",  
    player: "Frippe",
    shield: 1,
    armor: "soft Leather",
    armor_rating: 2,
    armor_penalty: 1,
    armor_bulk: 0,
    mv: 4 
};

export const player_Grim = {
    abilityList: [3,2,3 ,3 ,2,2,5,6,2,2,2,2,3,2,2,2,2,2,1],
    "Agility": [0,0,0,0,0],
    "Animal_Handling": [0,0,0,0],
    "Athletics":[0,0,0,0,0,0],
    "Awareness": [0,0],
    "Cunning": [0,0,0],
    "Deception": [0,0,0,0],
    "Endurance": [0,0],
    "Fighting": [4, 0, 0, 0, 0, 0, 0, 0, 0],
    "Healing": [0,0,0],
    "Knowledge": [0,0,0],
    "Marksmanship": [0,0,0,0],
    "Persuasion": [0,0,0,0,0,0,0],
    "Status": [0,0,0,0],
    "Stealth": [0,0],
    "Survival": [0,0,0,0],
    "Thievery": [0,0,0],
    "Warfare": [0,0,0],
    "Will": [0,0,0],
    "Language": [1],
    age: 27,
    house: "Torshalla", 
    name: "Grim Blodyxa",   
    player: "Pontus",
    shield: 0,
    armor: "hard Leather",
    armor_rating: 3,
    armor_penalty: 2,
    armor_bulk: 0,
    mv: 4 
};

export const player_Bjorn = {
    abilityList: [4,2,4,4,3,3,3,4,1,2,3,4,3,3,2,2,2,3,1],
    "Agility": [0,0,0,0,1],
    "Animal_Handling": [0,0,0,0],
    "Athletics":[0,0,0,0,0,0],
    "Awareness": [0,0],
    "Cunning": [0,0,0],
    "Deception": [0,1,0,0],
    "Endurance": [0,0],
    "Fighting": [0, 0, 0, 0, 3, 0, 0, 0, 0],
    "Healing": [0,0,0],
    "Knowledge": [0,0,0],
    "Marksmanship": [1,0,0,0],
    "Persuasion": [1,0,0,0,0,1,0],
    "Status": [0,0,0,0],
    "Stealth": [0,0],
    "Survival": [0,0,0,0],
    "Thievery": [0,0,0],
    "Warfare": [0,0,0],
    "Will": [0,0,0],
    "Language": [1],
    age: 21,
    house: "Torshalla", 
    name: "Björn 'Kungsbane' Svensson",
    player: "Martin", 
    shield: 2, 
    armor: "Ringmail",
    armor_rating: 4,
    armor_penalty: 2,
    armor_bulk: 1,
    mv: 4 
};

export const player_Ulv = {
    abilityList: [4,2,3,4,2,2,5,5,3,2,3,2,2,2,3,1,2,2,1],
    "Agility": [0,0,0,0,1],
    "Animal_Handling": [0,0,0,0],
    "Athletics":[0,0,0,1,0,0],
    "Awareness": [0,0],
    "Cunning": [0,0,0],
    "Deception": [0,0,0,0],
    "Endurance": [0,0],
    "Fighting": [3, 0, 0, 0, 0, 0, 0, 0, 0],
    "Healing": [0,0,2],
    "Knowledge": [0,0,0],
    "Marksmanship": [1,0,0,0],
    "Persuasion": [0,0,0,0,0,0,0],
    "Status": [0,0,0,0],
    "Stealth": [0,0],
    "Survival": [0,0,0,0],
    "Thievery": [0,0,0],
    "Warfare": [0,0,0],
    "Will": [0,0,0],
    "Language": [1],
    age: 20,
    house: "Torshalla", 
    name: "Ulv Torstensson", 
    player: "Martin 2", 
    shield: 2, 
    armor: "Ringmail",
    armor_rating: 4,
    armor_penalty: 2,
    armor_bulk: 1,
    mv: 4 
};